config/routes.rb
Rails.application.routes.draw do
  
  resources :articles do
    resources :comments,  only: [:create, :destroy, :update]
  end
  devise_for :users
  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments
    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 20}
    before_save :set_visits_count

    def update_visits_count
        self.update(visits_count: self.visits_count + 1)
    end

    private

    def set_visits_count
        self.visits_count ||= 0
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   before_action :authenticate_user!, except: [:show, :index]
   before_action :set_article, except: [:index, :new, :create]
    #GET /articles
    def index
        @articles = Article.all
   end
    #GET /articles/:id
    def show
        @article.update_visits_count
        @comment = Comment.new
    end
    #GET /articles/new
    def new
        @article = Article.new
    end
    def edit
    end
    #POST /articles
    def create
        @article = current_user.articles.new(title: params[:article][:title], 
                                body: params[:article][:body])
        if @article.save
            redirect_to @article
        else
            render :new
        end
    end
    #PUT /articles/:id
    def update
        if @article.update(title: params[:article][:title],
                            body: params[:article][:body])
            redirect_to @article
        else
            render :edit
        end
    end
    def destroy
        @article.destroy
        redirect_to articles_path
    end
    private
    def set_article
        @article = Article.find(params[:id])
    end
    def validate_user
        redirect_to new_user_session_path, notice: "Necesitas Iniciar sesión"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy, :show]
  before_action :set_article
  before_action :authenticate_user!


  # POST /comments
  # POST /comments.json
    def show
    end
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment.article }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article =  Article.find(params[:article_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
        <% @article.errors.full_messages.each do |message| %>
            <div class="be-red white">
                * <%= message %>
            </div>
        <%end%>
        <div class="field">
            <%= f.text_field :title, placeholder: "Título" , class:"form-control"%>
        </div>
        <div class="field">
            <%= f.text_area :body, placeholder: "Escribe aquí el artículo" , class:"form-control" , style:"height:250px;" %>
        </div>
        <div class="field">
            <%= f.submit "Guardar" , class:"btn be-red white large-padding" %>
        </div>
    <%end%>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
    <h1>Editar artículo</h1>
    <%= render "form" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
    <h1><%= link_to article.title, article %></h1>
    <div>
        <%= article.body %> - <%= link_to "Eliminar", article, method: :delete %>
    </div>
<%end%>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
    <h1>Crear artículo</h1>
    <%= form_for(@article) do |f| %>
        <% @article.errors.full_messages.each do |message| %>
            <div class="be-red white">
                * <%= message %>
            </div>
        <%end%>
        <div class="field">
            <%= f.text_field :title, placeholder: "Título" , class:"form-control"%>
        </div>
        <div class="field">
            <%= f.text_area :body, placeholder: "Escribe aquí el artículo" , class:"form-control" , style:"height:250px;" %>
        </div>
        <div class="field">
            <%= f.submit "Guardar" , class:"btn be-red white large-padding" %>
        </div>
    <%end%>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
    Visitas: <%= @article.visits_count %>
</p>
<div>
    <%= @article.body%>
</div>
<div class="field">
<h3>Comentarios</h3>
<%= render "comments/form" %>
<ul id="comments-box">
    <% @article.comments.each do |comment| %>
        <li>
            <%= comment.body %> - <%= comment.user.email %>
        </li>
    <%end%>
</ul>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment], remote: true, html: {id: "comments-form", :"data-type" => "json"}) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body, "Escriba su comentario" %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_navigation.html.erb
<header>
        <nav class="be-red white large-padding">
            <ul class="no-list row center-xs">
                <li class="col-md">
                    <h1 class="no-margin" id="logo">Blog Facilito</h1>
                </li>
                <li class="col-md">
                    <%= link_to "Inicio", root_path %>
                </li>
                <li class="col-md">
                    Diseño
                </li>
                <li class="col-md">
                    Programación
                </li>
                <li class="col-md">
                    Tecnología
                </li>
                <% if user_signed_in? %>
                    <li class="col-md">
                        <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
                    </li>
                <%else%>
                    <li class="col-md">
                        <%= link_to "Iniciar sesión", new_user_session_path %>
                    </li>
                    <li class="col-md">
                        <%= link_to "Crear Usuario", new_user_registration_path %>
                    </li>
                <%end%>
            </ul>
        </nav>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <%= csrf_meta_tags %>
      <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" href="//cdn.jsdelivr.net/flexboxgrid/6.1.1/flexboxgrid.min.css" type="text/css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>      
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>  
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Holaaa!!</h1>
<% [1,2,3,4].each do |number| %>
    <p>Numero: <%= number %></p>
<%end%>